=== grahamstark/tax_benefit_model_components/etc/parameters/dtds/parameters2.dtd
<!-- 
   a simple XML DTD for describing a Parameter system 
   new, much simplified version 14/12/2004

   ** This is the version for ADRS with various macro things and subjects and models **

   all the main elements have these:
    - Description: as much text as you like about whatever this is
    - Tooltip: about 1 sentence of plain text e.g. "increase this to raise revenue"
    - Journalese: 3-4 words, maybe usable in simple input forms e.g. "starting rate of tax"
-->

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description 
   lang CDATA "en"
   country CDATA "GB"
   type   (tooltip|journalese|description|label) "description"
>

<!ELEMENT UnitsString (#PCDATA)>

<!ATTLIST Description 
   lang CDATA "en"
   country CDATA "GB"
>

<!ELEMENT ParameterSystem (
                (
		Description | 		
		EditInfo |
                Parameter |
		ParameterSystem |
                ParameterSystemReference |
                EnumeratedType
                )*
                
          )
>


<!ELEMENT ParameterSystemReference (
                (
		Description |
		EditInfo
                )*
           )
>

<!ATTLIST ParameterSystemReference 
                       instanceName CDATA #REQUIRED
	               indexType (integer|enumerated|string) #IMPLIED 
	               indexEnumTypeRef IDREF #IMPLIED
                       indexSubsetRef IDREF #IMPLIED
	               type IDREF #REQUIRED
                       maximumSize NMTOKEN #IMPLIED
	               collectionType (set|map|list|singular) #IMPLIED
>


<!ATTLIST ParameterSystem
                       name CDATA #REQUIRED
                       id ID #IMPLIED
                       logicalType CDATA #IMPLIED
                       instanceName CDATA #IMPLIED
                       displayType (standard,final,referenceOnly) "standard"
                       subjects CDATA #IMPLIED
                       models  CDATA #IMPLIED
                       enabled (true|false) "true" 
>

<!-- a single Parameter (e.g an income tax allowance) -->


		

<!-- an optional set of actual Values associated with a Parameter -->

<!ELEMENT EditInfo EMPTY>

<!ATTLIST EditInfo
   type CDATA "default"
   output_index CDATA  #IMPLIED
   uprate (dont_uprate|rooker_wise|standard_uprate) "dont_uprate"
   country CDATA "GB"
   lang CDATA "en"
   currencyCode CDATA "GBP"
   next   NMTOKEN #IMPLIED
   display (hidden|normal|password|label_only) "normal"
   check (dont_check|warn|halt) "dont_check"
   min NMTOKEN "-9999999999.99"
   max  NMTOKEN "99999999999.99"
   prec NMTOKEN "2"
   format CDATA #IMPLIED
   match  CDATA #IMPLIED
   length NMTOKEN #IMPLIED
   asArray (true|false) "false"
   topset (true|false) "false"
   order  (asc|desc|none) "none"
   treatAsPercentage (true|false) "true"
   sumsTo100 (true|false) "false"
   macroVariableClass CDATA #IMPLIED 
   levelChangePossible (true|false) "true"
   isExogenous (true|false) "false"
   inputFileStartPos NMTOKEN #IMPLIED
   outputFileStartPos NMTOKEN #IMPLIED
   numVariables NMTOKEN #IMPLIED
   percentChangePossible (true|false) "false"
   realOutputFileStartPos NMTOKEN #IMPLIED
   exceptions  CDATA #IMPLIED 
   enabled (true|false) "true"
   access CDATA  "all"
>

<!-- 
    from  macroeconomic things mostly junk and could be got rid of in a well-ordered universe, but needed for the ADRS macro models  
-->

<!ELEMENT Parameter ( ( Description | EditInfo | UnitsString )* )>


<!ATTLIST Parameter 
		    name CDATA #IMPLIED
         	    instanceName CDATA #REQUIRED
                    indexType (none|integer|enumerated|string) "none"
        	     units  (timeless|day|week|month|year|percent|level|counts|money|rate|no_unit) "money"
                    type   (real|integer|enumerated|boolean|string|date|decimal) "real"
		     logicalType CDATA #IMPLIED
                    enumTypeRef IDREF #IMPLIED
                    indexEnumTypeRef IDREF #IMPLIED
                    indexSubsetRef IDREF #IMPLIED
                    collectionType (set|map|list|singular) "singular"
                    maximumSize NMTOKEN #IMPLIED
 		>


<!-- a simple EnumeratedType with numbers and Values -->
<!-- the id is a simple way which allows lots of Parameters to refer to it -->
<!ELEMENT EnumeratedType (Description*,EnumValue*, Subset* ) >

<!-- allow values="one two three", as well as a more complicated version -->
<!ATTLIST EnumeratedType 
          id ID #REQUIRED
          name   CDATA #IMPLIED
          Values CDATA #IMPLIED >

<!ELEMENT EnumValue (Description*, Text+)>
<!ATTLIST EnumValue 
          name   CDATA #REQUIRED
          value  NMTOKEN #IMPLIED
          default  (true|false) "false">
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text 
          lang CDATA 'en'
          country CDATA 'GB'                    
>


<!ELEMENT Subset ( Description* ) >

<!ATTLIST Subset 
          id ID  #REQUIRED
          start   CDATA #REQUIRED
          stop    CDATA #REQUIRED >

=== grahamstark/tax_benefit_model_components/etc/parameters/tests/policy_parameters_for_outputs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ParameterSystem SYSTEM "../dtds/parameters2.dtd" >

<!-- FIXME point to  SYSTEM "http://www.virtual-worlds.biz/dtds/parameters2.dtd"  -->


<ParameterSystem name="PolicyVariables" instanceName="policyVariables" enabled="true">
        <ParameterSystem name="SummaryBlock" instanceName="summaryBlock" enabled="true">
                <Description type="journalese" lang="en">Selected Macroeconomic Indicators</Description>
                <Description type="label" lang="en">Selected Macroeconomic Indicators</Description>
                <Description type="description" lang="en">Selected Macroeconomic Indicators</Description>
                <ParameterSystem name="SummaryBlockExpenditure" instanceName="summaryBlockExpenditure" enabled="true">
                        <Description type="journalese" lang="en">Real expenditure on GDP (Rbn at constant 2000 market prices)</Description>
                        <Description type="label" lang="en">Real expenditure (Rbn at constant 2000 market prices)</Description>
                        <Description type="description" lang="en">Real expenditure on GDP (Rbn at constant 2000 market prices)</Description>
                        <Parameter instanceName="gdpAtMarketPrices" type="real">
                                <Description type="journalese" lang="en">GDP at Market Prices</Description>
                                <Description type="label" lang="en">GDP at Market Prices</Description>
                                <Description type="description" lang="en">GDP at Market Prices</Description>
                                <EditInfo sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="18" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="privateConsumption" type="real">
                                <Description type="journalese" lang="en">Private consumption</Description>
                                <Description type="label" lang="en">Private consumption</Description>
                                <Description type="description" lang="en">Private consumption</Description>
                                <EditInfo sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="3" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="governmentConsumption" type="real">
                                <Description type="journalese" lang="en">Government consumption</Description>
                                <Description type="label" lang="en">Government consumption</Description>
                                <Description type="description" lang="en">Government consumption</Description>
                                <EditInfo sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="4" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="investment" type="real">
                                <Description type="journalese" lang="en">Investment</Description>
                                <Description type="label" lang="en">Investment</Description>
                                <Description type="description" lang="en">Investment</Description>
                                <EditInfo sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="7" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="exports" type="real">
                                <Description type="journalese" lang="en">Exports of goods  and  services</Description>
                                <Description type="label" lang="en">Exports of goods  and  services</Description>
                                <Description type="description" lang="en">Exports of goods  and  services</Description>
                                <EditInfo sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="12" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="imports" type="real">
                                <Description type="journalese" lang="en">Imports of goods  and  services</Description>
                                <Description type="label" lang="en">Imports of goods  and  services</Description>
                                <Description type="description" lang="en">Imports of goods  and  services</Description>
                                <EditInfo sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="17" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="grossDomesticExpenditure" type="real">
                                <Description type="journalese" lang="en">Gross Domestic Expenditure (GDE)</Description>
                                <Description type="label" lang="en">Gross Domestic Expenditure</Description>
                                <Description type="description" lang="en">Gross Domestic Expenditure (GDE)</Description>
                                <EditInfo sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="11" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                </ParameterSystem>
                <ParameterSystem name="SummaryBlockExpenditureGrowth" instanceName="summaryBlockExpenditureGrowth" enabled="true">
                        <Description type="journalese" lang="en">Real expenditure on GDP (% change)</Description>
                        <Description type="label" lang="en">Real expenditure Growth (% change)</Description>
                        <Description type="description" lang="en">Real expenditure on GDP (% change)</Description>
                        <Parameter instanceName="gdpAtMarketPrices" type="real">
                                <Description type="journalese" lang="en">GDP at Market Prices</Description>
                                <Description type="label" lang="en">GDP at Market Prices</Description>
                                <Description type="description" lang="en">GDP at Market Prices</Description>
                                <EditInfo treatAsPercentage="true" sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="10018" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="privateConsumption" type="real">
                                <Description type="journalese" lang="en">Private consumption</Description>
                                <Description type="label" lang="en">Private consumption</Description>
                                <Description type="description" lang="en">Private consumption</Description>
                                <EditInfo treatAsPercentage="true" sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="10003" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="governmentConsumption" type="real">
                                <Description type="journalese" lang="en">Government consumption</Description>
                                <Description type="label" lang="en">Government consumption</Description>
                                <Description type="description" lang="en">Government consumption</Description>
                                <EditInfo treatAsPercentage="true" sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="10004" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="investment" type="real">
                                <Description type="journalese" lang="en">Investment</Description>
                                <Description type="label" lang="en">Investment</Description>
                                <Description type="description" lang="en">Investment</Description>
                                <EditInfo treatAsPercentage="true" sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="10007" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="exports" type="real">
                                <Description type="journalese" lang="en">Exports of goods  and  services</Description>
                                <Description type="label" lang="en">Exports of goods  and  services</Description>
                                <Description type="description" lang="en">Exports of goods  and  services</Description>
                                <EditInfo treatAsPercentage="true" sumsTo100="false" macroVariableClass="3" levelChangePossible="true" isExogenous="false" outputFileStartPos="10012" numVariables="1" percentChangePossible="true"/>
                        </Parameter>
                        <Parameter instanceName="imports" type="real">
                                <Description type="journalese" lang="en">Imports of goods  and  services</Description>
                                <Description type="label" lang="en">Imports of goods  and  services</Description>
                                <Description type="description" lang="en">Imports of goods  and  services</Description>
